### ISSUE TITLE
Song Difficulty

### ISSUE THREAD

**Issue by chasehobbs** [Shadnix-was-taken/OhShape-SimpleSongInfo#1]
Song difficulty is still displaying at the old levels pre-electro party DLC. For example what is now Expert is still displayed as Hard.

**Comment by Shadnix-was-taken** [comment]
Thanks for reporting the issue. I'll try to take a look at it during the next couple of days.

**Comment by Shadnix-was-taken** [comment]
Sorry that it took so long. Updated and fixed in 1.2.0, which is now available in the release section.

Thanks again for reporting the issue.
